version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: dob-validator-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: dob_validator
      POSTGRES_USER: dob_user
      POSTGRES_PASSWORD: dob_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dob_user -d dob_validator"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-test:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DATABASE_URL=postgresql://dob_user:dob_password@postgres:5432/dob_validator
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres_data:
