version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: dob-validator-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dob_validator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile.dev
    container_name: dob-validator-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dob_validator
      - JWT_SECRET=your-jwt-secret
      - STELLAR_NETWORK=testnet
    volumes:
      - ../backend:/app/backend
      - ../shared:/app/shared
      - /app/backend/node_modules
      - /app/shared/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile.dev
    container_name: dob-validator-frontend
    ports:
      - "3000:3001"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3001
      - NEXT_PUBLIC_STELLAR_NETWORK=testnet
      - NEXT_PUBLIC_STELLAR_HORIZON_URL=https://horizon-testnet.stellar.org
    volumes:
      - ../frontend:/app/frontend
      - ../shared:/app/shared
      - /app/frontend/node_modules
      - /app/shared/node_modules
    depends_on:
      - backend

  backoffice:
    build:
      context: ..
      dockerfile: backoffice/Dockerfile.dev
    container_name: dob-validator-backoffice
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3001
      - NEXT_PUBLIC_STELLAR_NETWORK=testnet
      - NEXT_PUBLIC_STELLAR_HORIZON_URL=https://horizon-testnet.stellar.org
    volumes:
      - ../backoffice:/app/backoffice
      - ../shared:/app/shared
      - /app/backoffice/node_modules
      - /app/shared/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
