services:
  postgres:
    image: postgres:15-alpine
    container_name: dob-validator-db-prod
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-dob_validator}
      POSTGRES_USER: ${POSTGRES_USER:-dob_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dob_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-dob_user} -d ${POSTGRES_DB:-dob_validator}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dob-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: dob-validator-backend-prod
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-dob_user}:${POSTGRES_PASSWORD:-dob_password}@postgres:5432/${POSTGRES_DB:-dob_validator}?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - STELLAR_NETWORK=${STELLAR_NETWORK:-public}
      - STELLAR_HORIZON_URL=${STELLAR_HORIZON_URL:-https://horizon.stellar.org}
      - UPLOAD_DIR=uploads
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
      - PORT=3001
      - NODE_ENV=production
      - CORS_ORIGIN=${FRONTEND_URL}
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dob-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: dob-validator-frontend-prod
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${BACKEND_URL}
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dob-network

  backoffice:
    build:
      context: .
      dockerfile: backoffice/Dockerfile
    container_name: dob-validator-backoffice-prod
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "3002:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${BACKEND_URL}
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dob-network

  nginx:
    image: nginx:alpine
    container_name: dob-validator-nginx-prod
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backoffice
      - backend
    networks:
      - dob-network

volumes:
  postgres_data:
  uploads_data:

networks:
  dob-network:
    driver: bridge
