name: Deploy to Production

on:
  push:
    branches:
      - prod  # o la rama que quieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Ojo: NO hay script aquí, el comando se corre porque la clave tiene restriction
