name: Deploy to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Only run if PR is merged to main
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.***REMOVED*** }}
          vercel-org-id: ${{ secrets.***REMOVED*** }}
          vercel-project-id: ${{ secrets.***REMOVED*** }}
          working-directory: ./frontend
          vercel-args: "--prod"
